# Generated by Django 4.0.1 on 2022-02-19 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('category_no', models.AutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('course_no', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/courses/')),
                ('first_sub', models.CharField(choices=[('maths', 'maths'), ('english', 'english'), ('kiswahili', 'kiswahili'), ('chemistry', 'chemistry'), ('physics', 'physics'), ('biology', 'biology'), ('religion', 'religion'), ('business studies', 'business studies'), ('agriculture', 'agriculture'), ('music', 'music'), ('history and government', 'history and government'), ('home science', 'home science'), ('geography', 'geography'), ('electricity', 'electricity'), ('technical drawing', 'technical drawing'), ('computer studies', 'computer studies')], default='maths', max_length=30)),
                ('second_sub', models.CharField(choices=[('maths', 'maths'), ('english', 'english'), ('kiswahili', 'kiswahili'), ('chemistry', 'chemistry'), ('physics', 'physics'), ('biology', 'biology'), ('religion', 'religion'), ('business studies', 'business studies'), ('agriculture', 'agriculture'), ('music', 'music'), ('history and government', 'history and government'), ('home science', 'home science'), ('geography', 'geography'), ('electricity', 'electricity'), ('technical drawing', 'technical drawing'), ('computer studies', 'computer studies')], default='maths', max_length=30)),
                ('third_sub', models.CharField(choices=[('maths', 'maths'), ('english', 'english'), ('kiswahili', 'kiswahili'), ('chemistry', 'chemistry'), ('physics', 'physics'), ('biology', 'biology'), ('religion', 'religion'), ('business studies', 'business studies'), ('agriculture', 'agriculture'), ('music', 'music'), ('history and government', 'history and government'), ('home science', 'home science'), ('geography', 'geography'), ('electricity', 'electricity'), ('technical drawing', 'technical drawing'), ('computer studies', 'computer studies')], default='maths', max_length=30)),
                ('fourth_sub', models.CharField(choices=[('maths', 'maths'), ('english', 'english'), ('kiswahili', 'kiswahili'), ('chemistry', 'chemistry'), ('physics', 'physics'), ('biology', 'biology'), ('religion', 'religion'), ('business studies', 'business studies'), ('agriculture', 'agriculture'), ('music', 'music'), ('history and government', 'history and government'), ('home science', 'home science'), ('geography', 'geography'), ('electricity', 'electricity'), ('technical drawing', 'technical drawing'), ('computer studies', 'computer studies')], default='maths', max_length=30)),
                ('description', models.URLField(max_length=2083)),
                ('career', models.CharField(max_length=1000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='value that help users find course')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.category')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('Univ_no', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/universities')),
                ('category', models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=30)),
                ('location', models.CharField(max_length=200)),
                ('about', models.URLField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('entry_no', models.AutoField(primary_key=True, serialize=False)),
                ('cut_off', models.FloatField(default=0.0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.university')),
            ],
        ),
    ]
