# Generated by Django 3.2.12 on 2022-11-20 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('category_no', models.AutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('course_no', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/courses/')),
                ('first_sub', models.CharField(max_length=300)),
                ('second_sub', models.CharField(max_length=300)),
                ('third_sub', models.CharField(max_length=300)),
                ('fourth_sub', models.CharField(max_length=300)),
                ('career', models.CharField(max_length=1000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='value that help users find course')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.category')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('Univ_no', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/universities')),
                ('category', models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=30)),
                ('location', models.CharField(max_length=200)),
                ('about', models.URLField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('entry_no', models.AutoField(primary_key=True, serialize=False)),
                ('cut_off', models.FloatField(default=0.0)),
                ('cut_off_max', models.FloatField(default=12.0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.university')),
            ],
        ),
    ]
