# Generated by Django 4.0.1 on 2022-02-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='first_sub',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='course',
            name='fourth_sub',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='course',
            name='second_sub',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='course',
            name='third_sub',
            field=models.CharField(max_length=300),
        ),
    ]
