# Generated by Django 4.0.1 on 2022-02-20 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_first_sub_alter_course_fourth_sub_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
    ]
