# Generated by Django 4.0.1 on 2022-03-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='cut_off_max',
            field=models.FloatField(default=12.0),
        ),
    ]
