# Generated by Django 4.0.1 on 2022-03-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_entry_cut_off_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/universities/'),
        ),
    ]
