# Generated by Django 4.0.1 on 2022-03-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_university_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/universities'),
        ),
    ]
